"""Generate env/pokefirered_names.py from the pret/pokefirered map constants.

Run manually after updating third_party/pokefirered:
    uv run python scripts/generate_firered_names.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "third_party" / "pokefirered" / "include" / "constants" / "map_groups.h"
MAPS_DIR = ROOT / "third_party" / "pokefirered" / "data" / "maps"
OUT = ROOT / "env" / "pokefirered_names.py"

DEFINE_RE = re.compile(r"#define MAP_([A-Z0-9_]+)\s+\((\d+) \| \((\d+) << 8\)\)")
# FRLG map.json uses up/down/left/right; the harness uses compass directions (matching
# the Gen-1 MAP_CONNECTIONS table) so the agent's observation text is consistent.
DIR_MAP = {"up": "north", "down": "south", "left": "west", "right": "east"}

SPECIAL_WORDS = {"SS": "S.S.", "1F": "1F", "2F": "2F", "3F": "3F", "4F": "4F", "5F": "5F",
                 "6F": "6F", "7F": "7F", "8F": "8F", "9F": "9F", "10F": "10F", "11F": "11F",
                 "B1F": "B1F", "B2F": "B2F", "B3F": "B3F", "B4F": "B4F", "2P": "2P", "4P": "4P"}


def pretty(name: str) -> str:
    words = []
    for word in name.split("_"):
        if word in SPECIAL_WORDS:
            words.append(SPECIAL_WORDS[word])
        elif word.startswith("ROUTE") and word[5:].isdigit():
            words.append(f"Route {word[5:]}")
        else:
            words.append(word.capitalize())
    return " ".join(words)


def main() -> None:
    maps: dict[int, str] = {}
    name_to_id: dict[str, int] = {}
    for line in SRC.read_text().splitlines():
        match = DEFINE_RE.match(line.strip())
        if not match:
            continue
        name, num, group = match.group(1), int(match.group(2)), int(match.group(3))
        map_id = (group << 8) | num
        maps[map_id] = pretty(name)
        name_to_id[f"MAP_{name}"] = map_id

    # Mine warp tiles (doors/stairs) and outdoor connections from each map.json, mapping
    # the destination map constants back to ids — the FRLG analogue of MAP_WARPS /
    # MAP_CONNECTIONS in env/pokered_names.py.
    warps: dict[int, list[tuple[int, int, int | None]]] = {}
    connections: dict[int, dict[str, int]] = {}
    for map_json in sorted(MAPS_DIR.glob("*/map.json")):
        try:
            data = json.loads(map_json.read_text())
        except json.JSONDecodeError:
            continue
        self_id = name_to_id.get(data.get("id", ""))
        if self_id is None:
            continue
        warp_list = [
            (int(w["x"]), int(w["y"]), name_to_id.get(w.get("dest_map", "")))
            for w in (data.get("warp_events") or [])
        ]
        if warp_list:
            warps[self_id] = warp_list
        conn: dict[str, int] = {}
        for c in data.get("connections") or []:
            direction = DIR_MAP.get(c.get("direction", ""))
            dest = name_to_id.get(c.get("map", ""))
            if direction and dest is not None:
                conn[direction] = dest
        if conn:
            connections[self_id] = conn

    lines = [
        '"""Fire Red map id ((group << 8) | num) -> name, plus warp/connection tables.',
        "",
        "Generated by scripts/generate_firered_names.py from pret/pokefirered constants and",
        "data/maps/*/map.json. Do not edit by hand.",
        '"""',
        "",
        "FIRERED_MAP_NAMES: dict[int, str] = {",
    ]
    for map_id in sorted(maps):
        lines.append(f"    {map_id}: {maps[map_id]!r},")
    lines.append("}")
    lines.append("")
    lines.append("# Warp tiles: map_id -> [(x, y, dest_map_id | None)].")
    lines.append("FIRERED_MAP_WARPS: dict[int, list[tuple[int, int, int | None]]] = {")
    for map_id in sorted(warps):
        lines.append(f"    {map_id}: {warps[map_id]!r},")
    lines.append("}")
    lines.append("")
    lines.append("# Outdoor edge connections: map_id -> {direction: dest_map_id}.")
    lines.append("FIRERED_MAP_CONNECTIONS: dict[int, dict[str, int]] = {")
    for map_id in sorted(connections):
        lines.append(f"    {map_id}: {connections[map_id]!r},")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(maps)} maps, {len(warps)} with warps, {len(connections)} with connections)")


if __name__ == "__main__":
    main()
