"""Generate env/pokered_names.py from the pret/pokered disassembly in third_party/.

Run manually after updating third_party/pokered:
    uv run python scripts/generate_pokered_names.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POKERED = ROOT / "third_party" / "pokered"
OUT = ROOT / "env" / "pokered_names.py"

SPECIAL_WORDS = {
    "M": "♂",
    "F": "♀",
    "2F": "2F",
    "3F": "3F",
    "4F": "4F",
    "5F": "5F",
    "B1F": "B1F",
    "B2F": "B2F",
    "B3F": "B3F",
    "B4F": "B4F",
    "SS": "S.S.",
    "PC": "PC",
    "NW": "NW",
    "NE": "NE",
    "SW": "SW",
    "SE": "SE",
}


def pretty(name: str) -> str:
    words = []
    for word in name.split("_"):
        if word in SPECIAL_WORDS:
            words.append(SPECIAL_WORDS[word])
        elif word.startswith("ROUTE") and word[5:].isdigit():
            words.append(f"Route {word[5:]}")
        else:
            words.append(word.capitalize())
    out = " ".join(words)
    # NIDORAN_M -> "Nidoran♂" (gender sign attaches without a space)
    out = out.replace(" ♂", "♂").replace(" ♀", "♀")
    return out


def parse_species() -> dict[int, str]:
    text = (POKERED / "constants" / "pokemon_constants.asm").read_text()
    species: dict[int, str] = {}
    index = 0
    for line in text.splitlines():
        if re.match(r"\s*const_skip\b", line):
            index += 1
            continue
        match = re.match(r"\s*const\s+([A-Z0-9_]+)", line)
        if not match:
            continue
        name = match.group(1)
        if name != "NO_MON":
            species[index] = pretty(name)
        index += 1
    return species


def parse_dex_order() -> dict[int, str]:
    """National dex number -> name (1..151). Also the Gen 3 internal species ids."""
    text = (POKERED / "constants" / "pokedex_constants.asm").read_text()
    out: dict[int, str] = {}
    index = 0
    for line in text.splitlines():
        match = re.match(r"\s*const\s+DEX_([A-Z0-9_]+)", line)
        if not match:
            continue
        index += 1
        out[index] = pretty(match.group(1))
    return out


def parse_maps() -> dict[int, str]:
    text = (POKERED / "constants" / "map_constants.asm").read_text()
    maps: dict[int, str] = {}
    index = 0
    for line in text.splitlines():
        match = re.match(r"\s*map_const\s+([A-Z0-9_]+),", line)
        if not match:
            continue
        maps[index] = pretty(match.group(1))
        index += 1
    return maps


def main() -> None:
    species = parse_species()
    maps = parse_maps()
    dex = parse_dex_order()
    lines = [
        '"""Gen 1 internal species index -> name and map id -> name tables.',
        "",
        "Generated by scripts/generate_pokered_names.py from pret/pokered constants.",
        "Do not edit by hand.",
        '"""',
        "",
        "SPECIES_NAMES: dict[int, str] = {",
    ]
    for index in sorted(species):
        lines.append(f"    {index}: {species[index]!r},")
    lines.append("}")
    lines.append("")
    lines.append("MAP_NAMES: dict[int, str] = {")
    for index in sorted(maps):
        lines.append(f"    {index}: {maps[index]!r},")
    lines.append("}")
    lines.append("")
    lines.append("# National dex number -> name. Doubles as Gen 3 internal species ids 1..151.")
    lines.append("DEX_SPECIES_NAMES: dict[int, str] = {")
    for index in sorted(dex):
        lines.append(f"    {index}: {dex[index]!r},")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(species)} species, {len(maps)} maps, {len(dex)} dex)")


if __name__ == "__main__":
    main()
