"""Generate env/pokefirered_names.py from the pret/pokefirered map constants.

Run manually after updating third_party/pokefirered:
    uv run python scripts/generate_firered_names.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "third_party" / "pokefirered" / "include" / "constants" / "map_groups.h"
OUT = ROOT / "env" / "pokefirered_names.py"

DEFINE_RE = re.compile(r"#define MAP_([A-Z0-9_]+)\s+\((\d+) \| \((\d+) << 8\)\)")

SPECIAL_WORDS = {"SS": "S.S.", "1F": "1F", "2F": "2F", "3F": "3F", "4F": "4F", "5F": "5F",
                 "6F": "6F", "7F": "7F", "8F": "8F", "9F": "9F", "10F": "10F", "11F": "11F",
                 "B1F": "B1F", "B2F": "B2F", "B3F": "B3F", "B4F": "B4F", "2P": "2P", "4P": "4P"}


def pretty(name: str) -> str:
    words = []
    for word in name.split("_"):
        if word in SPECIAL_WORDS:
            words.append(SPECIAL_WORDS[word])
        elif word.startswith("ROUTE") and word[5:].isdigit():
            words.append(f"Route {word[5:]}")
        else:
            words.append(word.capitalize())
    return " ".join(words)


def main() -> None:
    maps: dict[int, str] = {}
    for line in SRC.read_text().splitlines():
        match = DEFINE_RE.match(line.strip())
        if not match:
            continue
        name, num, group = match.group(1), int(match.group(2)), int(match.group(3))
        maps[(group << 8) | num] = pretty(name)
    lines = [
        '"""Fire Red map id ((group << 8) | num) -> name table.',
        "",
        "Generated by scripts/generate_firered_names.py from pret/pokefirered constants.",
        "Do not edit by hand.",
        '"""',
        "",
        "FIRERED_MAP_NAMES: dict[int, str] = {",
    ]
    for map_id in sorted(maps):
        lines.append(f"    {map_id}: {maps[map_id]!r},")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(maps)} maps)")


if __name__ == "__main__":
    main()
